version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/ash -c 'yarn dev'
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - .:/vite-vue-ts-template
